# Devices common to GIXPCS and GISAXS experiments

# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- {creator: ophyd.sim.motor, name: sim_motor_xs}
- {creator: ophyd.sim.noisy_det, name: sim_det_xs}

common_9id.devices.AcsMotor:
# Grand Tube motors
- {name: "carriage_hor_bs_y",   prefix: "9idGT:m1", labels: ["motor", "baseline"]}
- {name: "eiger_hor_bs_y",      prefix: "9idGT:m2", labels: ["motor", "baseline"]}
- {name: "eiger_vert_bs_x",     prefix: "9idGT:m3", labels: ["motor", "baseline"]}
- {name: "mmpad_hor_bs_y",      prefix: "9idGT:m4", labels: ["motor", "baseline"]}
- {name: "mmpad_x",             prefix: "9idGT:m5", labels: ["motor", "baseline"]}
- {name: "mmpad_y",             prefix: "9idGT:m6", labels: ["motor", "baseline"]}
- {name: "eiger_vert_bs_y",     prefix: "9idGT:m7", labels: ["motor", "baseline"]}
#- {name: "",                   prefix: "9idGT:m8", labels: ["motor", "baseline"]}
- {name: "z_carriage",          prefix: "9idGT:m9", labels: ["motor", "baseline"]}
#- {name: "z_enc",              prefix: "9idGT:m10", labels: ["motor", "baseline"]}
- {name: "eiger_x",             prefix: "9idGT:m11", labels: ["motor", "baseline"]}
- {name: "eiger_y",             prefix: "9idGT:m12", labels: ["motor", "baseline"]}
#- {name: "eiger_x_enc",        prefix: "9idGT:m15", labels: ["motor", "baseline"]}
#- {name: "eiger_y_enc",        prefix: "9idGT:m16". labels: ["motor", "baseline"]}
ophyd.EpicsMotor:
- {name: "carriage_bs_top",     prefix: "9idGT:mcs2-02:m1", labels: ["motor", "baseline"]}
- {name: "carriage_bs_mid",     prefix: "9idGT:mcs2-02:m2", labels: ["motor", "baseline"]}
- {name: "carriage_bs_bot",     prefix: "9idGT:mcs2-02:m3", labels: ["motor", "baseline"]}
- {name: "eiger_vert_bs_y_ob",  prefix: "9idGT:mcs2-02:m4", labels: ["motor", "baseline"]}
- {name: "eiger_vert_bs_y_mid", prefix: "9idGT:mcs2-02:m5", labels: ["motor", "baseline"]}
- {name: "eiger_vert_bs_y_ib",  prefix: "9idGT:mcs2-02:m6", labels: ["motor", "baseline"]}
- {name: "eiger_hor_bs_x_top",  prefix: "9idGT:mcs2-01:m1", labels: ["motor", "baseline"]}
- {name: "eiger_hor_bs_x_top2", prefix: "9idGT:mcs2-01:m2", labels: ["motor", "baseline"]}
- {name: "eiger_hor_bs_x_top3", prefix: "9idGT:mcs2-01:m3", labels: ["motor", "baseline"]}
- {name: "eiger_hor_bs_x_bot",  prefix: "9idGT:mcs2-01:m4", labels: ["motor", "baseline"]}
- {name: "mmpad_hor_bs_x_top",  prefix: "9idGT:mcs2-01:m5", labels: ["motor", "baseline"]}
- {name: "mmpad_hor_bs_x_mid",  prefix: "9idGT:mcs2-01:m6", labels: ["motor", "baseline"]}
- {name: "mmpad_hor_bs_x_bot",  prefix: "9idGT:mcs2-01:m7", labels: ["motor", "baseline"]}


# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1
